export const CHANNELS = {
    LOGIN_ROOM: "LOGIN_ROOM",
    WAITING_ROOM: "WAITING_ROOM",
    SM_ROOM: "SM_ROOM",
    MAIN_ROOM: "MAIN_ROOM",
    NON_ATTENDEES_ROOM: "NON_ATTENDEES_ROOM",
    DISCONNECTED: "DISCONNECTED",
}