export const CHANNELS = {
    LOGIN_ROOM: "LOGIN_ROOM",
    WAITING_ROOM: "WAITING_ROOM",
    SM_ROOM: "SM_ROOM",
    MAIN_ROOM: "MAIN_ROOM",
    NON_ATTENDEES_ROOM: "NON_ATTENDEES_ROOM",
    DISCONNECTED: "DISCONNECTED",
    CREATE_ACCOUNT: "CREATE_ACCOUNT",
    CHANGE_PASSWORD: "CHANGE_PASSWORD",
    VERIFY: "VERIFY",
    REPLACE_ACCOUNTS: "REPLACE_ACCOUNTS",
}