export const CLIENT_EVENTS = {
    connect: 'connect',
    disconnect: 'disconnect',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    UPDATE_SHOW: 'UPDATE_SHOW',
    JOIN_ROOM: 'JOIN_ROOM',
    JOIN_CHANNEL: 'JOIN_CHANNEL',
    CREATE_ROOM: 'CREATE_ROOM',
    DELETE_ROOM: 'DELETE_ROOM',
    UPDATE_ROOM: 'UPDATE_ROOM',
    TOGGLE_SHOW_START: 'TOGGLE_SHOW_START'
};